spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    database: 7
    timeout: 10000

redisson:
  address: redis://127.0.0.1:6379
  master-name: mymaster
  password:
  sentinel-addresses: 10.47.91.83:26379,10.47.91.83:26380,10.47.91.83:26381
  use-sentinel: false
  timeout: 3000